### PR TITLE
Fix Tree.printDotGraph ignoring fd

### LINKED ISSUE #202: BUG: Parser.Tree#printDotGraph should honor fd
Currently the passed `fd` (first parameter) to `printDotGraph` is ignored and the fd for stderr is always set as I look
https://github.com/tree-sitter/node-tree-sitter/blob/master/src/tree.cc#L234.

### PR DESCRIPTION
**Pull request by segevfiner**
Fixes #202

### CODE REVIEW

File: src/tree.cc [hunk 1]
```diff
@@ -231,7 +231,16 @@ Napi::Value Tree::GetEditedRange(const Napi::CallbackInfo &info) {
...
 Napi::Value Tree::PrintDotGraph(const Napi::CallbackInfo &info) {
-  ts_tree_print_dot_graph(tree_, fileno(stderr));
+  int fd = fileno(stderr);
+
+  if (info.Length() > 1) {
+    if (!info[1].IsNumber()) {
+      throw TypeError::New(info.Env(), "Second argument must be a number");
+    }
+    fd = info[1].As<Number>().Int32Value();
+  }
```
Comment (amaanq) [inline src/tree.cc:241]: shouldn't we check the first arg for `Tree.printDotGraph`, not the second?

Comment (segevfiner) [reply src/tree.cc:241]: Ok whoops. Forgot to correct this.

Comment (amaanq) [reply src/tree.cc:241]: if you can, add a test too! ideally similar to the one in parser_test.js for `Parser.printDotGraphs`
